# 数据集配置
data:
  dataset: "FashionMNIST"  # [不可修改] 固定使用FashionMNIST数据集
  num_classes: 10          # [不可修改] FashionMNIST固定为10个类别
  input_size: 784         # [不可修改] 图像大小固定为28*28=784
  train_size: 60000       # [不可修改] 训练集大小固定为60000
  test_size: 10000        # [不可修改] 测试集大小固定为10000
  root_dir: "./data"      # [可修改] 可根据实际存储位置调整
  batch_size: 256         # [可修改] 建议值：16-512，根据GPU显存调整
  num_workers: 4          # [可修改] 建议设置为CPU核心数，过大可能导致内存压力

# 模型配置
model:
  type: "mlp"             # [可修改] 可选"softmax"或"mlp"，建议使用"mlp"获得更好性能
  hidden_units: [256, 128] # [可修改] 可调整层数和每层单元数，需要权衡计算资源和模型性能
  dropout_rate: 0.5       # [可修改] 建议范围0.2-0.5，过大可能影响训练效果

# 训练配置
training:
  num_epochs: 5           # [可修改] 建议范围5-50，根据训练收敛情况调整
  learning_rate: 0.1      # [可修改] 建议范围0.001-0.1，可根据训练情况调整
  weight_decay: 1e-4      # [可修改] 建议范围1e-5到1e-3，用于控制模型正则化
  device: "cuda"          # [可修改] 根据实际硬件选择"cuda"或"cpu"
  save_dir: "outputs/models" # [可修改] 模型保存路径，根据需要调整
  log_dir: "outputs/logs"   # [可修改] 日志保存路径，根据需要调整
  viz_dir: "outputs/visualizations" # [可修改] 可视化结果保存路径，根据需要调整

# 日志配置
logging:
  log_interval: 100       # [可修改] 每隔多少个batch打印一次日志，建议范围10-500
