# ResNet18 CIFAR-10 配置文件

# 运行模式设置
run_mode:
  mode: "evaluate"  # "train" 或 "evaluate"
  model_path: "outputs/models/best.pth"  # 评估模式时使用的模型路径
  resume_path: null  # 训练模式时恢复训练的检查点路径（可选）

# 数据设置
data:
  dataset: "cifar10"
  data_root: "./data/raw"  # 修正数据存储路径到正确的raw目录
  batch_size: 512
  num_workers: 4
  pin_memory: true
  
  # 数据增强参数
  transforms:
    train:
      random_horizontal_flip: 0.5
      random_crop:
        size: 32
        padding: 4
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  
  # 数据分割
  validation_split: 0.2
  shuffle: true
  random_seed: 42

# 模型设置
model:
  name: "resnet18"
  num_classes: 10
  input_channels: 3
  
  # ResNet18架构参数
  resnet:
    block_type: "basic"
    layers: [2, 2, 2, 2]  # ResNet18的层数配置
    initial_channels: 64
    use_pretrained: false  # 禁止使用预训练模型

# 训练设置
training:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 1e-4
  momentum: 0.9
  
  # 目标准确率设置（仅用于日志记录）
  target_accuracy: 0.90  # 验证集目标准确率 (90%)
  
  # 优化器
  optimizer: "adam"
  optimizer_params:
    betas: [0.9, 0.999]
    eps: 1e-8
  
  # 学习率调度
  scheduler: "cosine"
  scheduler_params:
    T_max: 100
    eta_min: 1e-6
  
  # 早停机制（主要的过拟合防止机制）
  early_stopping:
    patience: 10  # 增加耐心，给模型更多机会
    min_delta: 0.001  # 最小改善幅度
    monitor: "val_loss"  # 监控验证损失
    mode: "min"  # 损失最小化
  
  # 收敛检测（辅助监控）
  convergence:
    patience: 10
    threshold: 1e-5  # 更严格的收敛阈值
      # 过拟合警告（仅警告，不停止训练）
  overfitting:
    patience: 5
    train_val_gap_threshold: 0.1

# 保存设置
checkpoint:
  save_frequency: 10  # 每10个epoch保存一次
  save_best: true
  save_last: true
  monitor: "val_accuracy"
  mode: "max"
  max_checkpoints: 10  # 最多保留10个检查点文件（不包括best.pth）

# 日志设置
logging:
  level: "INFO"
  log_frequency: 100  # 每100个batch记录一次

# 可视化设置（所有可视化都会自动生成）
visualization: {}

# 设备设置
device:
  use_cuda: true
  mixed_precision: true

# 随机种子
random_seed: 42

# 输出路径 (相对于项目根目录)
paths:
  logs: "outputs/logs"
  models: "outputs/models"
  visualizations: "outputs/visualizations"
