# ResNet18 CIFAR-10 配置文件 - 参数修改指南
# 🟢 可安全修改  🟡 谨慎修改  🔴 不建议修改

# 运行模式设置
run_mode:
  mode: "evaluate"  # 🟢 可修改: "train" 或 "evaluate"
  model_path: "outputs/models/best.pth"  # 🟢 可修改: 评估模式时使用的模型路径
  resume_path: null  # 🟢 可修改: 训练模式时恢复训练的检查点路径（可选）

# 数据设置
data:
  dataset: "cifar10"  # 🔴 不可修改: 项目专为CIFAR-10设计
  data_root: "./data/raw"  # 🟡 谨慎修改: 数据存储路径，需确保路径存在
  batch_size: 512  # 🟢 可修改: 批次大小，影响显存使用和训练速度
  num_workers: 4  # 🟢 可修改: 数据加载线程数，根据CPU核心数调整
  pin_memory: true  # 🟢 可修改: 加速数据传输，GPU训练建议保持true
  
  # 数据增强参数
  transforms:
    train:
      random_horizontal_flip: 0.5  # 🟢 可修改: 水平翻转概率，0.0-1.0
      random_crop:
        size: 32  # 🔴 不可修改: CIFAR-10图像固定尺寸32x32
        padding: 4  # 🟢 可修改: 随机裁剪的填充像素，2-8像素合理
    normalize:
      mean: [0.485, 0.456, 0.406]  # 🔴 不可修改: CIFAR-10标准归一化均值
      std: [0.229, 0.224, 0.225]   # 🔴 不可修改: CIFAR-10标准归一化标准差
  
  # 数据分割
  validation_split: 0.2  # 🟢 可修改: 验证集比例，0.1-0.3合理
  shuffle: true  # 🟢 可修改: 是否随机打乱数据，训练建议保持true
  random_seed: 42  # 🟢 可修改: 随机种子，用于复现实验

# 模型设置
model:
  name: "resnet18"  # 🔴 不可修改: 项目专为ResNet18设计
  num_classes: 10  # 🔴 不可修改: CIFAR-10固定10个类别
  input_channels: 3  # 🔴 不可修改: CIFAR-10为RGB图像，3通道
  
  # ResNet18架构参数
  resnet:
    block_type: "basic"  # 🔴 不可修改: ResNet18使用BasicBlock
    layers: [2, 2, 2, 2]  # 🔴 不可修改: ResNet18的层数配置
    initial_channels: 64  # 🟡 谨慎修改: 初始通道数，修改会显著影响模型性能
    use_pretrained: false  # 🟢 可修改: 是否使用预训练权重，当前禁用

# 训练设置
training:
  epochs: 10  # 🟢 可修改: 训练轮数，根据需要调整
  learning_rate: 0.001  # 🟢 可修改: 学习率，关键超参数，0.0001-0.01合理
  weight_decay: 1e-4  # 🟢 可修改: 权重衰减，正则化参数，1e-5到1e-3合理
  momentum: 0.9  # 🟢 可修改: SGD动量，当前使用Adam时不生效
  
  # 目标准确率设置（仅用于日志记录）
  target_accuracy: 0.90  # 🟢 可修改: 目标准确率，0.80-0.95合理
  
  # 优化器
  optimizer: "adam"  # 🟢 可修改: "adam" 或 "sgd"
  optimizer_params:
    betas: [0.9, 0.999]  # 🟢 可修改: Adam的β参数
    eps: 1e-8  # 🟢 可修改: Adam的ε参数
    # 学习率调度
  scheduler: "cosine"  # 🟢 可修改: "cosine" 或 "step" 或 null
  scheduler_params:
    # Cosine调度器参数
    T_max: 100  # 🟢 可修改: 余弦退火的最大迭代数，通常设为总epochs
    eta_min: 1e-6  # 🟢 可修改: 最小学习率
    
    # Step调度器参数（当scheduler="step"时使用）
    step_size: 30  # 🟢 可修改: 每N个epoch降低学习率
    gamma: 0.1  # 🟢 可修改: 学习率衰减因子
  
  # 早停机制（主要的过拟合防止机制）
  early_stopping:
    patience: 10  # 🟢 可修改: 早停耐心值，3-20合理
    min_delta: 0.001  # 🟢 可修改: 最小改善幅度
    monitor: "val_loss"  # 🟡 谨慎修改: 监控指标，"val_loss"或"val_acc"
    mode: "min"  # 🟡 谨慎修改: 模式，与monitor对应
  
  # 收敛检测（辅助监控）
  convergence:
    patience: 10  # 🟢 可修改: 收敛检测耐心值
    threshold: 1e-5  # 🟢 可修改: 收敛阈值
  
  # 过拟合警告（仅警告，不停止训练）
  overfitting:
    patience: 5  # 🟢 可修改: 过拟合检测耐心值
    train_val_gap_threshold: 0.1  # 🟢 可修改: 训练验证准确率差距阈值

# 保存设置
checkpoint:
  save_best: true  # 🟢 可修改: 是否保存最佳模型
  save_last: true  # 🟢 可修改: 是否保存最后一个模型
  save_frequency: 5  # 🟢 可修改: 每N个epoch保存一次检查点
  monitor: "val_accuracy"  # 🟡 谨慎修改: 监控指标，需与代码逻辑匹配
  mode: "max"  # 🟡 谨慎修改: 模式，与monitor对应

# 日志设置
logging:
  level: "INFO"  # 🟢 可修改: "DEBUG", "INFO", "WARNING", "ERROR"
  log_frequency: 20  # 🟢 可修改: 每N个batch记录一次，1-100合理

# 可视化设置（所有可视化都会自动生成）
visualization: {}  # 🟢 可修改: 可添加可视化相关配置

# 设备设置
device:
  use_cuda: true  # 🟢 可修改: 是否使用GPU，有GPU建议保持true
  mixed_precision: true  # 🟢 可修改: 混合精度训练，节省显存

# 随机种子
random_seed: 42  # 🟢 可修改: 全局随机种子，用于复现实验

# 输出路径 (相对于项目根目录)
paths:
  logs: "outputs/logs"  # 🟡 谨慎修改: 日志输出路径
  models: "outputs/models"  # 🟡 谨慎修改: 模型保存路径
  visualizations: "outputs/visualizations"  # 🟡 谨慎修改: 可视化输出路径

# =============================================================================
# 重要提示和建议修改组合：
# =============================================================================

# 🚀 性能调优建议：
# 1. 调整学习率 (learning_rate): 0.0001-0.01
# 2. 调整批次大小 (batch_size): 128, 256, 512, 1024
# 3. 调整训练轮数 (epochs): 10-100
# 4. 调整权重衰减 (weight_decay): 1e-5 到 1e-3

# 🎯 常用修改场景：
# 
# 场景1: 快速测试
# - epochs: 5
# - batch_size: 256
# - target_accuracy: 0.80
# 
# 场景2: 高精度训练
# - epochs: 50
# - learning_rate: 0.0005
# - early_stopping.patience: 15
# - target_accuracy: 0.95
# 
# 场景3: 显存不足
# - batch_size: 128
# - mixed_precision: true
# - num_workers: 2

# ⚠️ 修改注意事项：
# 1. 修改架构相关参数前请确认代码兼容性
# 2. 路径修改后需确保目录存在
# 3. 监控指标修改需与代码逻辑一致
# 4. 某些参数组合可能导致训练不稳定
