# 数据生成配置
data:
  num_examples: 2048
  true_w: [1.5, -3.0]
  true_b: 2.4
  noise_sigma: 0.01
  features_mean: 0.0
  features_std: 1.0
  train_ratio: 0.8
  batch_size: 128
  seed: 106
  data_dir: "../data"  # 相对于src目录的路径

# 模型配置
model:
  input_dim: 2
  output_dim: 1

# 训练配置
training:
  num_epochs: 50
  learning_rate: 0.01
  device: "cuda"  # 可选: "cuda", "cpu"
  save_dir: "../outputs/models"
  log_dir: "../outputs/logs"
  viz_dir: "../outputs/visualizations"

# 日志配置
logging:
  log_interval: 10  # 每多少个epoch记录一次日志
